import { Theme } from "../theme/theme.slint";
export component ToggleSwitch inherits Rectangle {
    callback toggled;
    in-out property <string> text;
    in-out property <bool> checked;
    in-out property <bool> enabled <=> touch-area.enabled;

    width: 40px;
    height: 20px;
    border-width: 1px;
    vertical-stretch: 0;
    horizontal-stretch: 0;
    border-radius: root.height / 2;
    border-color: self.background.darker(25%);
    background: root.enabled ? (root.checked ? Theme.accent : white) : white;

    animate background { duration: 100ms; }

    bubble := Rectangle {
        height: bubble.width;
        width: root.height - 8px;
        border-radius: bubble.height / 2;
        y: 4px;
        x: 4px + self.a * (parent.width - bubble.width - 8px);

        property <float> a: root.checked ? 1 : 0;

        background: root.checked ? white : (root.enabled ? Theme.accent : gray);

        animate a, background {
            duration: 200ms;
            easing: ease;
        }
    }

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
        clicked => {
            root.checked = !root.checked;
            root.toggled();
        }
    }
}
