import { Theme } from "../../theme/theme.slint";
import { Icons } from "../../services/icons.slint";

export component TextField inherits Rectangle {
    in property <bool> enabled: true;
    in property <string> placeholder;
    in property <bool> show_icon: true;
    in property <length> icon_size: 12px;
    in property <image> source: Icons.search;
    in-out property <string> text <=> input.text;
    in-out property <bool> has-focus: input.has-focus;

    callback edited(string);
    callback accepted(string);

    width: 200px;
    height: 35px;
    border-width: 1px;
    background: Theme.bg_input;
    drop-shadow-color: Theme.shadow_glow; //accent_glow;
    drop-shadow-blur: input.has-focus ? 3px : 0px;
    border-radius: self.height * Theme.radius_full;
    border-color: input.has-focus ? Theme.accent : Theme.border_primary;

    HorizontalLayout {
        spacing: 8px;
        padding-left: 12px;
        padding-right: 12px;

        if show_icon: Image {
            source: source;
            width: icon_size;
            colorize: Theme.text_tertiary;
        }

        Rectangle {
            clip: true;

            input := TextInput {
                font-size: 12px;
                single-line: true;
                enabled: root.enabled;
                color: Theme.text_primary;
                vertical-alignment: center;
                edited => edited(self.text);
                accepted => {
                    input.clear-focus();
                    accepted(self.text);
                }

                // Placeholder Logic
                if (self.text == ""): Text {
                    x: 0px;
                    text: root.placeholder;
                    color: Theme.text_tertiary;
                    y: show_icon ? 12.5px : 10px;
                }
            }
        }
    }
}
