import { ScrollView } from "std-widgets.slint";
import { Theme } from "../../theme/theme.slint";

export component TextArea inherits Rectangle {
    in property <string> placeholder;
    in property <length> font-size: 0.82rem;
    in-out property <string> text <=> input.text;

    callback edited(string);

    clip: true;
    min-height: 100px;
    border-width: 1px;
    background: Theme.bg_input;
    border-radius: Theme.radius_md;
    drop-shadow-color: Theme.shadow_glow;
    drop-shadow-blur: input.has-focus ? 5px : 0px;
    border-color: input.has-focus ? Theme.accent : Theme.border_secondary;

    ScrollView {
        height: parent.height;
        viewport-height: input.preferred-height + 20px;

        VerticalLayout {
            padding: 10px;

            input := TextInput {
                wrap: word-wrap;
                single-line: false;
                font-size: font-size;
                min-height: root.height;
                edited => edited(self.text);

                if (self.text == ""): Text {
                    x: 0px;
                    y: 1px;
                    font-size: font-size;
                    text: root.placeholder;
                    color: Theme.text_tertiary;
                }
            }
        }
    }
}