
import { Theme } from "../../theme/theme.slint";
import { Icons } from "../../services/icons.slint";
import { HorizontalDivider } from "../divider/horizontal_divider.slint";

component CardHeader inherits HorizontalLayout {
    in property <string> title;
    in property <image> source;
    in property <bool> hasMore;

    callback moreClicked();

    spacing: 4px;
    padding: 15px;
    vertical-stretch: 0;

    Image {
        width: 17px;
        source: source;
        height: self.width;
        colorize: Theme.accent;
    }

    Text {
        text: title;
        font-size: 1rem;
        font-weight: 600;
        horizontal-stretch: 1;
        color: Theme.text_primary;
        vertical-alignment: center;
    }

    if hasMore:   Rectangle {

        ta := TouchArea {
            mouse-cursor: pointer;
            clicked => moreClicked();
        }

        HorizontalLayout {
            spacing: 3px;

            Text {
                text: "View All";
                font-size: 0.82rem;
                vertical-alignment: center;
                color: ta.has-hover ? Theme.accent : Theme.accent_light;
            }

            VerticalLayout {
                y: -1.5px;
                alignment: center;

                Image {
                    width: 10px;
                    source: Icons.arrowRight;
                    colorize: ta.has-hover ? Theme.accent : Theme.accent_light;
                }
            }
        }
    }
}

export component Card inherits Rectangle {
    in property <string> title;
    in property <image> source;
    in-out property <bool> hasMore: false;

    callback moreClicked();

    clip: true;
    border-width: 1px;
    background: Theme.bg_card;
    border-radius: Theme.radius_lg;
    border-color: Theme.border_primary;

    VerticalLayout {

        CardHeader {
            title: title;
            source: source;
            hasMore: hasMore;
            moreClicked => moreClicked();
        }

        HorizontalDivider {
            background: Theme.border_primary;
        }

        @children
    }
}
