
import { Theme } from "../../theme/theme.slint";
import { Icons } from "../../services/icons.slint";
import { HorizontalDivider } from "../divider/horizontal_divider.slint";

export component CardHeader inherits HorizontalLayout {
    in property <string> title;
    in property <image> source;

    padding: 15px;
    vertical-stretch: 0;
    alignment: space-between;

    VerticalLayout {
        alignment: center;

        HorizontalLayout {
            spacing: 4px;
    
            Image {
                width: 17px;
                source: source;
                height: self.width;
                colorize: Theme.accent;
            }
    
            Rectangle {
                width: txt.width;
    
                txt := Text {
                    y: 4px;
                    text: title;
                    font-size: 1rem;
                    font-weight: 600;
                    color: Theme.text_primary;
                    vertical-alignment: center;
                }
            }
        }
    }

    @children
}

export component Card inherits Rectangle {
    clip: true;
    border-width: 1px;
    background: Theme.bg_card;
    border-radius: Theme.radius_lg;
    border-color: Theme.border_primary;

    VerticalLayout {
        vertical-stretch: 1;

        @children
    }
}
