import { Theme } from "../../theme/theme.slint";
import { Icons } from "../../services/icons.slint";
import { Cleaner } from "../../global/cleaner_global.slint";
import { QuickAction } from "../../pages/dashboard/dashboard_data.slint";

export component RectCard inherits Rectangle {
    callback clicked();
    
    in property <brush> colorize: Theme.accent;
    in property <brush> source_bg: Theme.bg_card;
    in property <image> source: Icons.activeCleaner;
    
    in-out property <bool> has-hover: ta.has-hover;

    in property <string> title: "Card Title";
    in-out property <color> title_color: Theme.text_primary;

    in property <string> description: "Card Desc";
    in-out property <color> desc_color: Theme.text_tertiary;

    height: 56px;
    border-width: 1px;
    drop-shadow-blur: 0px;
    border-radius: Theme.radius_md;
    drop-shadow-color: Theme.accent;
    background: ta.has-hover ? Theme.bg_elevated : Theme.bg_tertiary;
    border-color: ta.has-hover ? Theme.border_secondary : Theme.border_primary;

    ta := TouchArea {
        clicked => clicked();
        mouse-cursor: pointer;
    }

    HorizontalLayout {
        spacing: 10px;
        padding-left: 10px;
        padding-right: 10px;

        VerticalLayout {
            width: 36px;
            alignment: center;

            Rectangle {
                clip: true;
                height: self.width;
                background: source_bg;
                width: root.height * 0.7;
                border-radius: Theme.radius_md;

                Image {
                    source: source;
                    colorize: colorize;
                    width: parent.width - 18px;
                }
            }
        }

        VerticalLayout {
            spacing: 3px;
            alignment: center;
            horizontal-stretch: 1;

            Text {
                text: title;
                font-weight: 600;
                font-size: 0.9rem;
                color: title_color;
            }

            if description != "":  Text {
                text: description;
                color: desc_color;
                font-size: 0.77rem;
            }
        }

        @children
    }
}
