import { Theme } from "../../theme/theme.slint";
import { Icons } from "../../services/icons.slint";
import { Cleaner } from "../../global/cleaner_global.slint";
import { QuickAction } from "../../pages/dashboard/dashboard_data.slint";

export component RectCard inherits VerticalLayout {
    in property <string> title: "Card Title";
    in property <string> description: "Card Desc";
    in property <image> source: Icons.activeCleaner;

    in-out property <bool> has-hover: ta.has-hover;
    in-out property <color> desc_color: Theme.text_tertiary;

    in-out property <length> _x <=> rect.x;
    in-out property <length> _drop-shadow-blur: 0px;
    in-out property <brush> _background <=> rect.background;
    in-out property <color> _drop-shadow-color: Theme.accent;
    in-out property <brush> _border-color <=> rect.border-color;

    height: 56px;

    rect := Rectangle {
        border-width: 1px;
        border-radius: Theme.radius_md;
        drop-shadow-blur: _drop-shadow-blur;
        drop-shadow-color: _drop-shadow-color;
        background: ta.has-hover ? Theme.bg_elevated : Theme.bg_tertiary;
        border-color: ta.has-hover ? Theme.border_secondary : Theme.border_primary;

        ta := TouchArea {
            mouse-cursor: pointer;
            clicked => {
            }
        }

        HorizontalLayout {
            spacing: 10px;
            padding-left: 10px;
            padding-right: 10px;

            VerticalLayout {
                width: 36px;
                alignment: center;

                Rectangle {
                    clip: true;
                    width: 36px;
                    height: self.width;
                    background: Theme.bg_card;
                    border-radius: Theme.radius_md;

                    Image {
                        source: source;
                        colorize: Theme.accent;
                        width: parent.width - 18px;
                    }
                }
            }

            VerticalLayout {
                spacing: 3px;
                alignment: center;
                horizontal-stretch: 1;

                Text {
                    text: title;
                    font-weight: 600;
                    font-size: 0.9rem;
                    color: Theme.text_primary;
                }

                Text {
                    text: description;
                    color: desc_color;
                    font-size: 0.77rem;
                }
            }

            @children
        }
    }
}
