
import { Theme } from "../../theme/theme.slint";
import { Icons } from "../../services/icons.slint";
import { StatData } from "../../pages/dashboard/dashboard_data.slint";

export component StatCard inherits Rectangle {
    in property <StatData> data;

    border-width: 1px;
    background: Theme.bg_card;
    border-radius: Theme.radius_lg;
    border-color: ta.has-hover ? Theme.accent : Theme.border_primary;

    ta := TouchArea { }

    HorizontalLayout {
        spacing: 13px;
        padding: 15px;

        Rectangle {
            width: 40px;
            height: self.width;
            border-radius: Theme.radius_md;
            background: Theme.accent.with-alpha(0.12);

            Image {
                source: data.icon;
                colorize: Theme.accent;
                width: parent.width - 25px;
            }
        }

        VerticalLayout {
            spacing: 2px;
            alignment: center;
            horizontal-stretch: 1;

            Text {
                text: data.value;
                font-weight: 800;
                font-size: 1.65rem;
                letter-spacing: -1px;
                color: Theme.text_primary;
            }

            Text {
                text: data.label;
                font-weight: 500;
                font-size: 0.8rem;
                color: Theme.text_secondary;
            }
        }

        VerticalLayout {
            alignment: center;

            Rectangle {
                border-radius: self.height * Theme.radius_full;
                background: data.is_grey ? Theme.bg_tertiary : Theme.success_bg;

                HorizontalLayout {
                    spacing: 2px;
                    padding-top: 4px;
                    padding-left: 6px;
                    padding-right: 6px;
                    padding-bottom: 3px;

                    Image {
                        width: 8px;
                        source: data.trend-icon;
                        colorize:  data.is_grey ? Theme.text_tertiary : Theme.success;
                    }

                    Text {
                        font-size: 0.72rem;
                        text: data.trend-label;
                        vertical-alignment: center;
                        color: data.is_grey ? Theme.text_tertiary : Theme.success;
                    }
                }
            }
        }
    }
}
