import { StartScan } from "./phase/start_scan/start_scan.slint";
import { StartClean } from "./phase/start_clean/start_clean.slint";
import { PhaseProcessing } from "./phase/phase_processing/processing.slint";
import { ScanAndCleanPageData, ScanCleanPhase } from "scan_clean_data.slint";
import {
    CleanSuccessfulPhase,
} from "./phase/successful/clean_successful.slint";

export component ScanAndCleanPage inherits VerticalLayout {

    if ScanAndCleanPageData.current_phase == ScanCleanPhase.StartScan:  StartScan {
        on_start_scan(val) => {
            if (val) {
                ScanAndCleanPageData.current_phase = ScanCleanPhase.ProcessingPhase;
            }
        }
    }

    if ScanAndCleanPageData.current_phase == ScanCleanPhase.StartClean:   StartClean {
        re_scan => {
            ScanAndCleanPageData.current_phase = ScanCleanPhase.StartScan;
        }
        start_clean => {
            ScanAndCleanPageData.current_phase = ScanCleanPhase.StartClean;
        }
    }

    if ScanAndCleanPageData.current_phase == ScanCleanPhase.ProcessingPhase:   PhaseProcessing {
        on_finished(nxt_phase) => {
            ScanAndCleanPageData.current_phase = nxt_phase;
        }
    }

    if  ScanAndCleanPageData.current_phase == ScanCleanPhase.CleanSuccessful:   CleanSuccessfulPhase {
        new_scan => {
            ScanAndCleanPageData.current_phase = ScanCleanPhase.StartScan;
        }
        dashboard => {
            //
        }
    }
}
