export global Icons {
    out property <image> edit: @image-url("../../assets/icons/edit.png");
    out property <image> code: @image-url("../../assets/icons/code.png");
    out property <image> plus: @image-url("../../assets/icons/plus.png");
    out property <image> appIcon: @image-url("../../assets/icons/app_icon.png");
    out property <image> arrowRight: @image-url("../../assets/icons/arrow-right.png");
    
    // Theme
    out property <image> sun: @image-url("../../assets/icons/theme/sun.png");
    out property <image> moon: @image-url("../../assets/icons/theme/moon.png");
    
    // Tabs
    out property <image> puzzle: @image-url("../../assets/icons/tabs/puzzle.png");
    out property <image> search: @image-url("../../assets/icons/tabs/search.png");
    out property <image> terminal: @image-url("../../assets/icons/tabs/terminal.png");
    out property <image> settings: @image-url("../../assets/icons/tabs/settings.png");
    out property <image> dashboard: @image-url("../../assets/icons/tabs/dashboard.png");
    
    // Body Header
    out property <image> bolt: @image-url("../../assets/icons/body_header/bolt.png");
    out property <image> notification: @image-url("../../assets/icons/body_header/notification.png");

    // Card Icons
    out property <image> AvailableCleaners: puzzle;
    out property <image> recent: @image-url("../../assets/icons/card/history.png");
    out property <image> quickAction: @image-url("../../assets/icons/card/rocket.png");

    // Quick Action Icons
    out property <image> quickClean: appIcon;
    out property <image> newScan: @image-url("../../assets/icons/quick_action/scan.png");
    out property <image> addCleaner: @image-url("../../assets/icons/quick_action/add.png");
    out property <image> documentation: @image-url("../../assets/icons/quick_action/book.png");

    // Card Stats
    out property <image> activeCleaner: puzzle;
    out property <image> totalCleaned: @image-url("../../assets/icons/stats_card/minus.png");
    out property <image> projectsFound: @image-url("../../assets/icons/stats_card/arrow-up.png");
    out property <image> spaceRecoverable: @image-url("../../assets/icons/stats_card/arrow-up.png");

    // Paths
    out property <image> file: @image-url("../../assets/icons/paths/file.png");
    out property <image> folder: @image-url("../../assets/icons/paths/folder.png");

    // Scam & Clean
    out property <image> eye: @image-url("../../assets/icons/scan_clean/eye.png");
    out property <image> blind: @image-url("../../assets/icons/scan_clean/blind.png");
    out property <image> sliders: @image-url("../../assets/icons/scan_clean/sliders.png");
    out property <image> flow-chart: @image-url("../../assets/icons/scan_clean/flow-chart.png");

    // Activity Log
    out property <image> trash: @image-url("../../assets/icons/activity_log/trash.png");
    out property <image> download: @image-url("../../assets/icons/activity_log/download.png");

    // settings 
    out property <image> bug: @image-url("../../assets/icons/settings/bug.png");
    out property <image> info: @image-url("../../assets/icons/settings/info.png");
    out property <image> github: @image-url("../../assets/icons/settings/github.png");
    out property <image> shield: @image-url("../../assets/icons/settings/shield.png");
    out property <image> palette: @image-url("../../assets/icons/settings/palette.png");

    // Notification
    out property <image> close: @image-url("../../assets/icons/notification/close.png");
    out property <image> error: @image-url("../../assets/icons/notification/error.png");
    out property <image> warning: @image-url("../../assets/icons/notification/warning.png");
    out property <image> success: @image-url("../../assets/icons/notification/success.png");
    out property <image> info_bold: @image-url("../../assets/icons/notification/info_bold.png");
}
