export global Icons {
    out property <image> sun: @image-url("../../assets/icons/sun.png");
    out property <image> moon: @image-url("../../assets/icons/moon.png");
    out property <image> appIcon: @image-url("../../assets/icons/app_icon.png");

    // Tabs
    out property <image> puzzle: @image-url("../../assets/icons/tabs/puzzle.png");
    out property <image> search: @image-url("../../assets/icons/tabs/search.png");
    out property <image> terminal: @image-url("../../assets/icons/tabs/terminal.png");
    out property <image> settings: @image-url("../../assets/icons/tabs/settings.png");
    out property <image> dashboard: @image-url("../../assets/icons/tabs/dashboard.png");
    
    // Body Header
    out property <image> bolt: @image-url("../../assets/icons/body_header/bolt.png");
    out property <image> notification: @image-url("../../assets/icons/body_header/notification.png");
}
