import { Theme } from "../../theme/theme.slint";
export component IconButton inherits Rectangle {
    in property <image> icon;
    in property <length> size: 35px;
    in property <length> icon_size: 20px;

    in property <brush> border: Theme.border_primary;
    in property <brush> border_hover: Theme.border_secondary;

    in property <brush> bg: Theme.bg_input;
    in property <brush> bg_hover: Theme.bg_tertiary;

    in property <brush> colorize: Theme.text_secondary;
    in property <brush> colorize_hover: Theme.text_primary;

    callback clicked;

    width: size;
    height: size;
    border-width: 1px;
    border-radius: Theme.radius_md;
    background: ta.has-hover ? root.bg_hover : root.bg;
    border-color: ta.has-hover ? root.border_hover : root.border;

    ta := TouchArea {
        mouse-cursor: MouseCursor.pointer;
        clicked => root.clicked();
    }

    Image {
        source: root.icon;
        width: root.icon_size;
        height: root.icon_size;
        colorize: ta.has-hover ? root.colorize_hover : root.colorize;
    }

    @children
}
