import { Theme } from "../../theme/theme.slint";

export component TextIconButton inherits Rectangle {
    in property <string> text;
    in property <image> source;
    in property <length> icon_size: 14px;
    in property <length> horizontal-padding: 10px;

    callback clicked();

    height: 35px;
    background: Theme.accent;
    border-radius: Theme.radius_md;

    ta := TouchArea {
        mouse-cursor: pointer;
        clicked => root.clicked();
    }

    HorizontalLayout {
        spacing: 6px;
        padding-left: horizontal-padding;
        padding-right: horizontal-padding;

        Image {
            source: source;
            colorize: white;
            width: icon_size;
        }

        Text {
            y: 1px;
            text: text;
            font-weight: 600;
            font-size: 0.9rem;
            vertical-alignment: center;
        }
    }
}
