import { Theme } from "../../theme/theme.slint";
export component TextButton inherits Rectangle {
    in property <string> text;
    in property <color> text_color: white;
    in property <bool> has-hover: ta.has-hover;
    in property <length> horizontal-padding: 10px;


    callback clicked();

    height: 35px;
    background: Theme.accent;
    border-radius: Theme.radius_md;

    ta := TouchArea {
        mouse-cursor: pointer;
        clicked => root.clicked();
    }

    HorizontalLayout {
        spacing: 6px;
        padding-left: horizontal-padding;
        padding-right: horizontal-padding;

        Text {
            y: 1px;
            text: text;
            font-weight: 600;
            color: text_color;
            font-size: 0.9rem;
            vertical-alignment: center;
        }
    }
}
