import { Theme } from "../../theme/theme.slint";

export component TextIconButton inherits Rectangle {
    in property <string> text;
    in property <image> source;
    in property <length> icon_size: 14px;
    in property <color> icon_color: white;
    in property <color> text_color: white;
    in property <bool> has-hover: ta.has-hover;
    in property <length> horizontal-padding: 10px;

    callback clicked();

    height: 35px;
    background: Theme.accent;
    border-radius: Theme.radius_md;

    ta := TouchArea {
        mouse-cursor: pointer;
        clicked => root.clicked();
    }

    HorizontalLayout {
        spacing: 6px;
        padding-left: horizontal-padding;
        padding-right: horizontal-padding;

        Image {
            source: source;
            width: icon_size;
            colorize: icon_color;
        }

        Text {
            y: 1px;
            text: text;
            font-weight: 550;
            color: text_color;
            font-size: 0.9rem;
            vertical-alignment: center;
        }
    }
}
