import { DashboardAdapter } from "./data.slint";
import { Card } from "../../components/card.slint";
import { Icons } from "../../services/icons.slint";
import { StatCard } from "../../components/stat_card.slint";
import { HorizontalBox, ScrollView } from "std-widgets.slint";

export component DashboardPage inherits Flickable {
    horizontal-stretch: 1;
    min-width: layout.min-width + 40px;

    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        horizontal-stretch: 1;

        layout := HorizontalLayout {
            spacing: 15px;
            for data in DashboardAdapter.stats: StatCard {
                data: data;
            }
        }

        HorizontalLayout {
            spacing: 15px;

            Card {
                source: Icons.bolt;
                title: "Quick Actions";

                VerticalLayout {
                    spacing: 0px;
                    padding: 15px;
                }
            }

            Card {
                source: Icons.moon;
                title: "Recent Activity";

                Rectangle {
                    min-height: 200px;
                }
            }
        }

        Card {
            source: Icons.notification;
            title: "Available Cleaners";

            Rectangle {
                min-height: 200px;
            }
        }
    }
}
