import { Icons } from "../../services/icons.slint";

export enum PathType{
    File,
    Folder
}

export struct CleanDetect {
    path: string,
    label: string,
    type: PathType,
}

export struct CleanTarget {
    safe: bool,
    path: string,
    label: string,
    type: PathType,
}

export struct Cleaner {
    id: string,
    icon: image,
    name: string,
    color: color,
    description: string,
    detect: [CleanDetect],
    clean_command: string,
    restore_command: string,
    estimated_savings: string,
    clean_targets: [CleanTarget],
}

export global CleanersData {
    callback add_new_cleaner(string);
    callback edit_existing_cleaner(Cleaner);

    in-out property <bool> show_model: false;

    out property <[{key: string, desc: string}]> schema_demo: [
        {
            key: "id",
            desc: "Unique identifier",
        },
        {
            key: "name",
            desc: "Display name",
        },
        {
            key: "icon",
            desc: "Font Awesome class",
        },
        {
            key: "color",
            desc: "Hex accent color",
        },
        {
            key: "detect []",
            desc: "Directories or Files that identify this project",
        },
        {
            key: "clean_targets []",
            desc: "What to delete",
        },
        {
            key: "restore_command",
            desc: "How to restore after cleaning",
        }
    ];

    in-out property <[Cleaner]> cleaners: [
        {
            id: "my-custom",
            color: #FF6B6B,
            name: "My Custom Cleaner",
            icon: Icons.activeCleaner,
            estimated_savings: "100MB - 1GB",
            restore_command: "your-restore-command",
            description: "Describe what this cleaner does",
            detect:[
                {
                    label: "",
                    path: "pubspec.yaml",
                    type: PathType.File,
                },
                {
                    label: "",
                    path: ".dart_tool",
                    type: PathType.Folder,
                },
                {
                    label: "",
                    path: "build",
                    type: PathType.Folder,
                },
            ],
            clean_targets: [
                {
                    label: "",
                    safe: true,
                    path: "ios/ Pods",
                    type: PathType.Folder,
                },
                {
                    label: "",
                    safe: false,
                    path: ".packages",
                    type: PathType.File,
                },
                {
                    label: "",
                    safe: true,
                    path: "ios/ .symlinks",
                    type: PathType.Folder,
                }
            ],
        }
    ];
}
