import { Icons } from "../../services/icons.slint";

export global CleanersData {
    in-out property <bool> show_model: false;

    out property <[{key: string, desc: string}]> schema_demo: [
        {
            key: "id",
            desc: "Unique identifier",
        },
        {
            key: "name",
            desc: "Display name",
        },
        {
            key: "icon",
            desc: "Font Awesome class",
        },
        {
            key: "color",
            desc: "Hex accent color",
        },
        {
            key: "detect []",
            desc: "Directories or Files that identify this project",
        },
        {
            key: "clean_targets []",
            desc: "What to delete",
        },
        {
            key: "restore_command",
            desc: "How to restore after cleaning",
        }
    ];
}
