
import { Icons } from "../services/icons.slint";

export struct ActivityStruct {
    tag: string,
    icon: image,
    time: string,
    title: string,
    sub_title: string,
}

export global GlobalRecentActivity {
    in-out property <[ActivityStruct]> activity: [
        {
            tag: "clean",
            time: "2d ago",
            icon: Icons.activeCleaner,
            time: "Cleaning Complete",
            sub_title: "8 projects cleaned · 4.2 GB recovered",
        },
    ];
}
