import { Icons } from "../services/icons.slint";

export enum PathType{
    File,
    Folder
}

export struct CleanDetect {
    path: string,
    label: string,
    type: PathType,
}

export struct CleanTarget {
    safe: bool,
    path: string,
    label: string,
    type: PathType,
}

export struct Cleaner {
    id: string,
    icon: image,
    name: string,
    color: color,
    description: string,
    detect: [CleanDetect],
    clean_command: string,
    restore_command: string,
    estimated_savings: string,
    clean_targets: [CleanTarget],
}

export global CleanerGlobal {
    in-out property <[Cleaner]> cleaners: [
        {
            id: "my-custom",
            color: #FF6B6B,
            name: "My Custom Cleaner",
            icon: Icons.activeCleaner,
            estimated_savings: "100MB - 1GB",
            restore_command: "your-restore-command",
            description: "Describe what this cleaner does",
            detect:[
                {
                    label: "",
                    path: "pubspec.yaml",
                    type: PathType.File,
                },
                {
                    label: "",
                    path: ".dart_tool",
                    type: PathType.Folder,
                },
                {
                    label: "",
                    path: "build",
                    type: PathType.Folder,
                },
            ],
            clean_targets: [
                {
                    label: "",
                    safe: true,
                    path: "ios/ Pods",
                    type: PathType.Folder,
                },
                {
                    label: "",
                    safe: false,
                    path: ".packages",
                    type: PathType.File,
                },
                {
                    label: "",
                    safe: true,
                    path: "ios/ .symlinks",
                    type: PathType.Folder,
                }
            ],
        }
    ];
}
