import { Theme } from "../../theme/theme.slint";
export component VerticalDivider {
    in property <length> thickness: 1px;
    in property <length> height_size: 100px;
    in property <brush> color: Theme.border_secondary;

    width: root.thickness;
    height: root.height_size;

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: root.color;
    }
}
