import { Theme } from "../../../../theme/theme.slint";
import { Icons } from "../../../../services/icons.slint";
import { ScanCleanPhase } from "../../scan_clean_data.slint";
import { ActivityData } from "../../../activity/activity_data.slint";
import { TerminalLog } from "../../../../components/terminal_log.slint";

//============================
//
//============================
export component OrbitalProgress inherits Rectangle {
    in property <bool> animating: true;
    in property <string> progress_text: "58%";

    // Outer Ring (mc-orbit-ring)
    width: 100px;
    height: 100px;
    border-width: 2px;
    background: transparent;
    border-radius: self.width / 2;
    border-color: Theme.accent_dark.brighter(10%);

    // The rotation property we will animate
    property <angle> rotation_angle: 0deg;

    // Indefinite loop for the rotation
    init => {
        if (animating) {
            rotation_angle = 360deg;
        }
    }

    animate rotation_angle {
        duration: 3s;
        iteration-count: -1; // Loop forever
    }

    // Middle Ring (mc-ring-2)
    Rectangle {
        width: 80%;
        height: 80%;
        border-width: 1px;
        background: transparent;
        border-radius: self.width / 2;
        transform-rotation: -rotation_angle;
        border-color: @linear-gradient(60deg, Theme.bg_tertiary.brighter(40%), Theme.text_tertiary);
    }

    // Orbiting Dot
    // We rotate a container, which swings the dot around the center
    Rectangle {
        width: 100%;
        height: 100%;
        transform-rotation: root.rotation_angle;

        // The actual dot
        Rectangle {
            width: 10px;
            height: 10px;
            background: Theme.accent;
            y: -self.height / 2 + 1px; // Positioned on the top edge of the ring
            border-radius: self.width / 2;
            x: parent.width / 2 - self.width / 2;
        }
    }

    Rectangle {
        width: 60%;
        height: 60%;
        background: Theme.bg_card;
        border-radius: self.width / 2;

        Text {
            font-weight: 700;
            font-size: 1.5rem;
            text: progress_text;
            color: Theme.text_primary;
            vertical-alignment: center;
            horizontal-alignment: center;
            y: (parent.height / 2) - (self.height / 2) + 1.5px;
        }
    }
}

export component PhaseProcessing inherits VerticalLayout {
    callback on_finished(ScanCleanPhase);

    spacing: 10px;
    padding: 15px;

    //~~~~~~~~~~~~~~~~~~~~~~~~`
    HorizontalLayout {
        spacing: 20px;
        alignment: start;
        vertical-stretch: 0;
        padding-bottom: 10px;
        horizontal-stretch: 1;

        OrbitalProgress { }

        VerticalLayout {
            spacing: 8px;
            alignment: center;

            Text {
                font-weight: 600;
                font-size: 1.25rem;
                color: Theme.text_primary;
                text: "Scanning filesystem...";
            }

            HorizontalLayout {
                spacing: 10px;

                HorizontalLayout {
                    spacing: 3px;

                    Image {
                        width: 12px;
                        source: Icons.terminal;
                        colorize: Theme.text_tertiary;
                    }

                    Text {
                        y: 1px;
                        text: "00:01";
                        color: Theme.text_tertiary;
                    }
                }

                HorizontalLayout {
                    spacing: 3px;

                    Image {
                        width: 12px;
                        source: Icons.folder;
                        colorize: Theme.text_tertiary;
                    }

                    Text {
                        y: 1px;
                        text: "~/";
                        color: Theme.text_tertiary;
                    }
                }
            }
        }
    }

    //~~~~~~~~~~~~~~~~~~~~~~~~`
    Rectangle {
        clip: true;
        height: 5px;
        border-radius: 5px;
        background: Theme.bg_card;
        HorizontalLayout {

            Rectangle {
                width: 80%;
                border-top-right-radius: 5px;
                border-bottom-right-radius: 5px;
                background: @linear-gradient(90deg, Theme.accent_dark, Theme.accent_light);
            }
        }
    }

    //~~~~~~~~~~~~~~~~~~~~~~~~`
    TerminalLog {
        vertical-stretch: 1;
        logs: ActivityData.logs;
        background: Theme.bg_sidebar;
    }
}
